// Auto-generated template navigation
export const templatePages = [
  { slug: 'constructor-2', title: 'LATIN PROGRESSION CONSTRUCTOR' },
  { slug: 'constructor-deconstructor', title: 'LATIN PROGRESSION' },
  { slug: 'constructor', title: 'LATIN PROGRESSION CONSTRUCTOR' },
  { slug: 'common-base-word', title: 'LATIN PROGRESSION' },
  { slug: 'construct-and-match', title: 'LATIN PROGRESSION' },
  { slug: 'deconstructor', title: 'LATIN PROGRESSION DECONSTRUCTOR' },
  { slug: 'fill-in-the-morph--paragraph', title: 'LATIN PROGRESSION' },
  { slug: 'fill-in-the-morph--sentences', title: 'LATIN PROGRESSION' },
  { slug: 'how-do-you-say', title: 'LATIN PROGRESSION HOW DO YOU SAY?' },
  { slug: 'latin-progression-primer--chameleon-roots', title: 'LATIN PROGRESSION PRIMER -- Chameleon Roots' },
  { slug: 'morph-morph-match-3', title: 'LATIN PROGRESSION' },
  { slug: 'morph-morph-match', title: 'LATIN PROGRESSION' },
  { slug: 'morph-morph-match2', title: 'LATIN PROGRESSION' },
  { slug: 'morph-match-2', title: 'LATIN PROGRESSION MORPH MATCH' },
  { slug: 'morph-match', title: 'LATIN PROGRESSION MORPH MATCH' },
  { slug: 'morph-sort', title: 'LATIN PROGRESSION MORPH SORT' },
  { slug: 'morph-spell', title: 'LATIN PROGRESSION MORPH SPELL' },
  { slug: 'morph-which', title: 'LATIN PROGRESSION' },
  { slug: 'morph-match--chameleons', title: 'LATIN PROGRESSION' },
  { slug: 'morph-match-definitions', title: 'LATIN PROGRESSION' },
  { slug: 'primer-1', title: 'LATIN PROGRESSION PRIMER 1' },
  { slug: 'primer-2', title: 'LATIN PROGRESSION PRIMER 2' },
  { slug: 'part-of-speech-sort', title: 'LATIN PROGRESSION' },
  { slug: 'parts-of-speech', title: 'LATIN PROGRESSION: PARTS OF SPEECH' },
  { slug: 'review', title: 'LATIN PROGRESSION REVIEW' },
  { slug: 'sort-and-spell', title: 'LATIN PROGRESSION' },
  { slug: 'spelling-chaining--instructor-only', title: 'Educational Template' },
  { slug: 'spelling-chaining', title: 'LATIN PROGRESSION - SPELLING CHAINING' },
  { slug: 'spelling-review', title: 'LATIN PROGRESSION' },
  { slug: 'spoken-chaining--instructor-only', title: 'LATIN PROGRESSION SPOKEN CHAINING' },
  { slug: 'spoken-chaining', title: 'LATIN PROGRESSION' },
  { slug: 'suffix-completer', title: 'LATIN PROGRESSION SUFFIX COMPLETER' },
  { slug: 'suffix-transformer', title: 'LATIN PROGRESSION SUFFIX TRANSFORMER' },
  { slug: 'unscramble', title: 'LATIN PROGRESSION UNSCRAMBLE' },
  { slug: 'word-builder', title: 'LATIN PROGRESSION WORD BUILDER' },
  { slug: 'word-meaning', title: 'LATIN PROGRESSION WORD MEANING' },
];